---
- name: "Install Fish dependencies"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ fish_package_dependencies }}"
  become: true

- name: "Add Fish repositiory"
  ansible.builtin.apt_repository:
    repo: "{{ fish_ubuntu_ppa }}"
    update_cache: true
    state: "present"
  become: true

- name: "Install Fish"
  ansible.builtin.package:
    name: "fish"
    state: "present"
  become: true

- name: "Set Fish as default shell"
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: "/usr/bin/fish"
  become: true

- name: "Remove old version of Oh My Fish"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/omf"
    state: "absent"
  changed_when: false

- name: "Download Oh My Fish install script"
  ansible.builtin.get_url:
    url: "{{ fish_oh_my_fish_install_script_url }}"
    dest: "/tmp/oh-my-fish-install.sh"
    mode: "755"
  changed_when: false

- name: "Install or update Oh My Fish"
  ansible.builtin.command:
    cmd: "/tmp/oh-my-fish-install.sh --noninteractive -y"
    creates: "{{ fish_oh_my_fish_install_location }}"

- name: "Remove Oh My Fish install script"
  ansible.builtin.file:
    path: "/tmp/oh-my-fish-install.sh"
    state: "absent"
  changed_when: false

- name: "Install Oh My Fish packages"
  ansible.builtin.command:
    cmd: "fish -c 'omf install {{ item }}'"
    creates: "{{ fish_oh_my_fish_install_location }}/pkg/{{ item }}"
  with_items: "{{ fish_oh_my_fish_packages }}"
