---
- name: "Install Fish dependencies"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ fish_package_dependencies }}"
  become: true

- name: "Add Fish repositiory"
  ansible.builtin.apt_repository:
    repo: "{{ fish_ubuntu_ppa }}"
    update_cache: true
    state: "present"
  become: true

- name: "Install Fish"
  ansible.builtin.package:
    name: "fish"
    state: "present"
  become: true

- name: "Set Fish as default shell"
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: "/usr/bin/fish"
  become: true

- name: "Check if Fish configuration already exists"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/fish"
  register: "current_fish_config"

- name: "Remove existing Fish configuration"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    state: "absent"
  when: "current_fish_config.stat.exists and not current_fish_config.stat.islnk"

- name: "Install Fish configuration"
  stow:
    package: "fish"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "present"

- name: "Download Fisher"
  ansible.builtin.get_url:
    url: "{{ fish_fisher_install_url }}"
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
    mode: "0644"

- name: "Install Fisher plugins"
  ansible.builtin.shell:
    cmd: "fisher install {{ item.name }}"
    executable: "/usr/bin/fish"
    creates: "{{ item.path }}"
  with_items: "{{ fish_fisher_plugins }}"
