---
- name: "Remove Fisher plugins"
  ansible.builtin.shell:
    cmd: "fisher remove {{ item.name }}"
    executable: "/usr/bin/fish"
  with_items: "{{ fish_fisher_plugins }}"
  changed_when: false

- name: "Reset default shell to Bash"
  ansible.builtin.user:
    name: "{{ current_user }}"
    shell: "/bin/bash"
  become: true

- name: "Remove Fish"
  ansible.builtin.package:
    name: "fish"
    state: "absent"
  become: true

- name: "Remove Fish repositiory"
  ansible.builtin.apt_repository:
    repo: "{{ fish_ubuntu_ppa }}"
    state: "absent"
  become: true

- name: "Remove Fish configuration"
  stow:
    package: "fish"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "absent"
