---
fish_ubuntu_ppa: "ppa:fish-shell/release-3"
fish_package_dependencies:
  - "gnupg"
fish_fisher_install_url: "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"
fish_fisher_plugins:
  - name: "jorgebucaran/fisher"
    path: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
  - name: "edc/bass"
    path: "{{ ansible_env.HOME }}/.config/fish/functions/bass.fish"
