packages:
  - "apache2-utils"
  - "ca-certificates"
  - "clang"
  - "curl"
  - "dnsutils"
  - "ffmpeg"
  - "gettext"
  - "git"
  - "htop"
  - "inetutils-traceroute"
  - "make"
  - "musl"
  - "ncdu"
  - "net-tools"
  - "rsync"
  - "unzip"
  - "vim"
  - "wget"
  - "zip"
