---
- name: "Remove Lazygit"
  ansible.builtin.file:
    path: "{{ lazygit_location }}"
    state: "absent"

- name: "Remove Lazygit configuration"
  stow:
    package: "lazygit"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "absent"
