---
docker_gpg_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_gpg_key_location: "/etc/apt/keyrings/docker.gpg"
docker_repository: "deb [signed-by={{ docker_gpg_key_location }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_package_dependencies:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "gnupg"
docker_packages:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"
  - "docker-buildx-plugin"
  - "docker-compose-plugin"
