---
lazygit_latest_release_url: "https://api.github.com/repos/jesseduffield/lazygit/releases/latest"
lazygit_folder_location: "{{ ansible_env.HOME }}/.local/bin"
lazygit_location: "{{ lazygit_folder_location }}/lazygit"
