[tools]

# Shell
"aqua:fish-shell/fish-shell" = { version = "latest", postinstall = "rm -rf $HOME/.local/bin/fish && ln -sf $MISE_TOOL_INSTALL_PATH/fish $HOME/.local/bin/fish" }
starship = "latest"

# Tools
"aqua:axllent/mailpit" = "latest"
aws-cli = "latest"
bat = "latest"
btop = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
helix = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
ripgrep = "latest"
"aqua:boyter/scc" = "latest"
terraform = "latest"
yazi = "latest"
yt-dlp = "latest"
zoxide = "latest"
watchexec = "latest"

# Misc
usage = "latest"

# Programming languages and tools.
python = "latest"
ansible = "latest"
pipx = "latest"
poetry = "latest"
ruff = "latest"
uv = "latest"

node = "lts"
pnpm = "latest"
"npm:mjml" = "latest"
oxfmt = "latest"
oxlint = "latest"

rust = "stable"
