[tools]

# Shell
"aqua:fish-shell/fish-shell" = { version = "latest", postinstall = "rm -rf $HOME/.local/bin/fish && ln -sf $MISE_TOOL_INSTALL_PATH/fish $HOME/.local/bin/fish" }
starship = "latest"

# Tools
"aqua:axllent/mailpit" = "latest"
bat = "latest"
btop = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
ripgrep = "latest"
yt-dlp = "latest"
zoxide = "latest"

# Misc
usage = "latest"
