---
disableStartupPopups: true

gui:
  nerdFontsVersion: "3"
  border: "rounded"
  timeFormat: "02/01/2006 15:04"
  shortTimeFormat: "02/01/2006 15:04"
  theme:
    selectedLineBgColor:
      - "#181a1f"

git:
  autoFetch: false

keybinding:
  universal:
    quit: "<esc>"
    return: "q"

customCommands:
  - key: "Z"
    context: "global"
    command: "git reset --soft HEAD~"
    loadingText: "Undoing last commit..."
    description: "Undo last commit"
    prompts:
      - type: "confirm"
        title: "Undo last commit"
        body: "Are you sure you want to undo the last commit?"
