# ---------------------------------------------------------------------------- #
#                        MrBin99 - Poetry Configuration                        #
# ---------------------------------------------------------------------------- #

[virtualenvs]
in-project = true
