---
- name: "Remove Git configuration"
  stow:
    package: "git"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "absent"

- name: "Remove package"
  ansible.builtin.package:
    name: "git"
    state: "absent"
  become: true
