---
- name: "Install Kubectl dependencies"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ kubernetes_kubectl_package_dependencies }}"
  become: true

- name: "Dowload Kubectl GPG key"
  ansible.builtin.get_url:
    url: "{{ kubernetes_kubectl_gpg_key_url }}"
    dest: "{{ kubernetes_kubectl_gpg_key_location }}"
    mode: "0644"
  become: true
  changed_when: true

- name: "Convert Kubectl GPG key to ASCII"
  ansible.builtin.shell:
    cmd: "set -o pipefail && cat {{ kubernetes_kubectl_gpg_key_location }} | gpg --yes --dearmor -o {{ kubernetes_kubectl_gpg_key_location }}"
    executable: "/bin/bash"
  become: true
  changed_when: true

- name: "Add Kubectl repository"
  ansible.builtin.apt_repository:
    repo: "{{ kubernetes_kubectl_repository }}"
    state: "present"
    filename: "kubectl"
    update_cache: true
  become: true

- name: "Install Kubectl packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ kubernetes_kubectl_packages }}"
  become: true

- name: "Install Kubectl Fish completions"
  ansible.builtin.shell:
    cmd: "kubectl completion fish > {{ ansible_env.HOME }}/.config/fish/completions/kubectl.fish"
    executable: "/usr/bin/fish"
  changed_when: true
