---
- name: "Download Kubectl"
  ansible.builtin.get_url:
    url: "{{ kubernetes_kubectl_download_url }}"
    dest: "{{ kubernetes_kubectl_install_location }}"
    mode: "0755"

- name: "Install Kubectl Fish completions"
  ansible.builtin.shell:
    cmd: "kubectl completion fish > {{ ansible_env.HOME }}/.config/fish/completions/kubectl.fish"
    executable: "/usr/bin/fish"
  changed_when: true
