---
- name: "Download Kubectl"
  ansible.builtin.get_url:
    url: "{{ kubernetes_kubectl_download_url }}"
    dest: "{{ kubernetes_kubectl_install_location }}"
    mode: "0755"

- name: "Install Kubectl Fish completions"
  ansible.builtin.shell:
    cmd: "kubectl completion fish > {{ ansible_env.HOME }}/.config/fish/completions/kubectl.fish"
    executable: "/usr/bin/fish"
  changed_when: true

- name: "Remove old Helm installation"
  ansible.builtin.file:
    path: "{{ kubernetes_helm_install_location }}"
    state: "absent"
  become: true

- name: "Download Helm install script"
  ansible.builtin.get_url:
    url: "{{ kubernetes_helm_install_script_url }}"
    dest: "/tmp/helm.sh"
    mode: "755"

- name: "Install or update Helm"
  ansible.builtin.command:
    cmd: "/tmp/helm.sh --no-sudo"
    creates: "{{ kubernetes_helm_install_location }}"
  become: true

- name: "Remove Helm install script"
  ansible.builtin.file:
    path: "/tmp/helm.sh"
    state: "absent"

- name: "Install Helm Fish completions"
  ansible.builtin.shell:
    cmd: "helm completion fish > {{ ansible_env.HOME }}/.config/fish/completions/helm.fish"
    executable: "/usr/bin/fish"
  changed_when: true

- name: "Remove old Kind installation"
  ansible.builtin.file:
    path: "{{ kubernetes_kind_location }}"
    state: "absent"
  become: true

- name: "Get Kind latest version"
  ansible.builtin.shell:
    cmd: "set -o pipefail && curl -s {{ kubernetes_kind_latest_release_url }} | jq -r '.assets | map(select(.browser_download_url | contains(\"linux-amd64\"))) | first | .browser_download_url'"
    executable: "/bin/bash"
  register: "kind_download_url"
  changed_when: false

- name: "Download Kind"
  ansible.builtin.get_url:
    url: "{{ kind_download_url.stdout }}"
    dest: "{{ kubernetes_kind_location }}"
    mode: "0755"
  when: "kind_download_url.stdout"

- name: "Install Kind Fish completions"
  ansible.builtin.shell:
    cmd: "kind completion fish > {{ ansible_env.HOME }}/.config/fish/completions/kind.fish"
    executable: "/usr/bin/fish"
  changed_when: true
