---
- name: "Dowload Terraform GPG key"
  ansible.builtin.get_url:
    url: "{{ terraform_gpg_key_url }}"
    dest: "{{ terraform_gpg_key_location }}"
    mode: "0644"
  become: true
  changed_when: true

- name: "Convert Terraform GPG key to ASCII"
  ansible.builtin.shell:
    cmd: "set -o pipefail && cat {{ terraform_gpg_key_location }} | gpg --yes --dearmor -o {{ terraform_gpg_key_location }}"
    executable: "/bin/bash"
  become: true
  changed_when: true

- name: "Add Terraform repository"
  ansible.builtin.apt_repository:
    repo: "{{ terraform_repository }}"
    state: "present"
    filename: "terraform"
    update_cache: true
  become: true

- name: "Install Terraform packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ terraform_packages }}"
  become: true

- name: "Install Terraform Fish completions"
  ansible.builtin.shell:
    cmd: "terraform -install-autocomplete"
    executable: "/usr/bin/fish"
    creates: "{{ ansible_env.HOME }}/.config/fish/completions/terraform.fish"
