---
kubernetes_kubectl_latest_version_url: "https://dl.k8s.io/release/stable.txt"
kubernetes_kubectl_download_url: "https://dl.k8s.io/release/{{ lookup('ansible.builtin.url', kubernetes_kubectl_latest_version_url) }}/bin/linux/amd64/kubectl"
kubernetes_kubectl_install_location: "{{ ansible_env.HOME }}/.local/bin/kubectl"
