---
- name: "Install utility packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ utilities_packges }}"
  become: true

- name: "Install Btop configuration"
  stow:
    package: "btop"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "present"

- name: "Install MailHog"
  ansible.builtin.get_url:
    url: "{{ utilities_mailhog_download_url }}"
    dest: "{{ utilities_mailhog_location }}"
    mode: "0755"
