---
- name: "Remove MailHog"
  ansible.builtin.file:
    path: "{{ utilities_mailhog_location }}"
    state: "absent"

- name: "Remove Btop configuration"
  stow:
    package: "btop"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "absent"

- name: "Remove utility packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "absent"
  with_items: "{{ utilities_packges }}"
  become: true
