---
- name: "Install Docker dependencies"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ docker_package_dependencies }}"
  become: true

- name: "Dowload Docker GPG key"
  ansible.builtin.get_url:
    url: "{{ docker_gpg_key_url }}"
    dest: "{{ docker_gpg_key_location }}"
    mode: "0644"
  become: true
  changed_when: true

- name: "Convert Docker GPG key to ASCII"
  ansible.builtin.shell:
    cmd: "set -o pipefail && cat {{ docker_gpg_key_location }} | gpg --yes --dearmor -o {{ docker_gpg_key_location }}"
    executable: "/bin/bash"
  become: true
  changed_when: true

- name: "Add Docker repository"
  ansible.builtin.apt_repository:
    repo: "{{ docker_repository }}"
    state: "present"
    filename: "docker"
    update_cache: true
  become: true

- name: "Install Docker packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ docker_packages }}"
  become: true
  notify: "restart docker services"

- name: "Create Docker group"
  ansible.builtin.group:
    name: "docker"
    state: "present"
  become: true

- name: "Add user to Docker group"
  ansible.builtin.user:
    name: "{{ current_user }}"
    groups: "docker"
    append: true
  become: true

- name: "Install Docker Fish completions"
  ansible.builtin.shell:
    cmd: "docker completion fish > {{ ansible_env.HOME }}/.config/fish/completions/docker.fish"
    executable: "/usr/bin/fish"
  changed_when: true
