---
- name: "Download Starship install script"
  ansible.builtin.get_url:
    url: "{{ starship_install_script_url }}"
    dest: "/tmp/starship_install.sh"
    mode: "755"

- name: "Make sure Starship install location exists"
  ansible.builtin.file:
    path: "{{ starship_install_location }}"
    state: "directory"
    mode: "0755"

- name: "Remove old version of Starship if exists"
  ansible.builtin.file:
    path: "{{ starship_install_location }}/starship"
    state: "absent"

- name: "Install or update Starship"
  ansible.builtin.command:
    cmd: "/tmp/starship_install.sh -y -b {{ starship_install_location }}"
    creates: "{{ starship_install_location }}/starship"

- name: "Remove Starship install script"
  ansible.builtin.file:
    path: "/tmp/starship_install.sh"
    state: "absent"

- name: "Install Starship configuration"
  stow:
    package: "starship"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "present"

- name: "Install Starship completions for Fish"
  ansible.builtin.shell:
    cmd: "starship completions fish > {{ starship_fish_completions_location }}"
  changed_when: true
