---
- name: "Install and configure new development environment"
  hosts: "all"
  gather_facts: true

  vars:
    modules_path: "{{ cwd }}/modules"
    current_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

  tasks:
    - name: "Include role 'stow'"
      ansible.builtin.include_role:
        name: "stow"
        tasks_from: "install"

    - name: "Create all needed directories"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: "directory"
        mode: "0755"
      with_items:
        - ".config"
        - ".local"
        - ".local/bin"

    - name: "Include WSL check file"
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/includes/wsl.yml"

    - name: "Include role 'wsl'"
      ansible.builtin.include_role:
        name: "wsl"
        tasks_from: "install"
      when: "is_wsl"

    - name: "Include role 'git'"
      ansible.builtin.include_role:
        name: "git"
        tasks_from: "install"

    - name: "Include role 'bash'"
      ansible.builtin.include_role:
        name: "bash"
        tasks_from: "install"

    - name: "Include role 'fish'"
      ansible.builtin.include_role:
        name: "fish"
        tasks_from: "install"

    - name: "Include role 'utilities'"
      ansible.builtin.include_role:
        name: "utilities"
        tasks_from: "install"

    - name: "Include role 'lazygit'"
      ansible.builtin.include_role:
        name: "lazygit"
        tasks_from: "install"

    - name: "Include role 'wezterm'"
      ansible.builtin.include_role:
        name: "wezterm"
        tasks_from: "install"

    - name: "Include role 'wezterm' (Windows)"
      ansible.builtin.include_role:
        name: "wezterm"
        tasks_from: "install_windows"
      when: "is_wsl"

    - name: "Include role 'starship'"
      ansible.builtin.include_role:
        name: "starship"
        tasks_from: "install"

    - name: "Include role 'docker'"
      ansible.builtin.include_role:
        name: "docker"
        tasks_from: "install"

    - name: "Include role 'rust'"
      ansible.builtin.include_role:
        name: "rust"
        tasks_from: "install"

    - name: "Include role 'python'"
      ansible.builtin.include_role:
        name: "python"
        tasks_from: "install"

    - name: "Include role 'node'"
      ansible.builtin.include_role:
        name: "node"
        tasks_from: "install"

    - name: "Include role 'php'"
      ansible.builtin.include_role:
        name: "php"
        tasks_from: "install"

    - name: "Include role 'terraform'"
      ansible.builtin.include_role:
        name: "terraform"
        tasks_from: "install"

    - name: "Include role 'kubernetes'"
      ansible.builtin.include_role:
        name: "kubernetes"
        tasks_from: "install"

    - name: "Include role 'nvim'"
      ansible.builtin.include_role:
        name: "nvim"
        tasks_from: "install"

    - name: "Include role 'fish'"
      ansible.builtin.include_role:
        name: "fish"
        tasks_from: "update_completions"
