---
- name: "Install and configure new development environment"
  hosts: "all"
  gather_facts: true
  tasks:
    - name: "Include role 'stow'"
      ansible.builtin.include_role:
        name: "stow"
        tasks_from: "install"
