---
- name: "Install and configure new development environment"
  hosts: "all"
  gather_facts: true

  vars:
    modules_path: "{{ cwd }}/modules"
    current_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

  tasks:
    - name: "Include role 'stow'"
      ansible.builtin.include_role:
        name: "stow"
        tasks_from: "install"

    - name: "Create all needed directories"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: "directory"
        mode: "0755"
      with_items:
        - ".config"
        - ".local"
        - ".local/bin"

    - name: "Include role 'git'"
      ansible.builtin.include_role:
        name: "git"
        tasks_from: "install"

    - name: "Include role 'bash'"
      ansible.builtin.include_role:
        name: "bash"
        tasks_from: "install"

    - name: "Include role 'fish'"
      ansible.builtin.include_role:
        name: "fish"
        tasks_from: "install"

    - name: "Include role 'starship'"
      ansible.builtin.include_role:
        name: "starship"
        tasks_from: "install"

    - name: "Include role 'fish'"
      ansible.builtin.include_role:
        name: "fish"
        tasks_from: "update_completions"
