---
- name: "Remove development environment"
  hosts: "all"
  gather_facts: true

  vars:
    modules_path: "{{ cwd }}/modules"
    current_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

  tasks:
    - name: "Include role 'python'"
      ansible.builtin.include_role:
        name: "python"
        tasks_from: "uninstall"

    - name: "Include role 'rust'"
      ansible.builtin.include_role:
        name: "rust"
        tasks_from: "uninstall"

    - name: "Include role 'docker'"
      ansible.builtin.include_role:
        name: "docker"
        tasks_from: "uninstall"

    - name: "Include role 'starship'"
      ansible.builtin.include_role:
        name: "starship"
        tasks_from: "uninstall"

    - name: "Include role 'fish'"
      ansible.builtin.include_role:
        name: "fish"
        tasks_from: "uninstall"

    - name: "Include role 'bash'"
      ansible.builtin.include_role:
        name: "bash"
        tasks_from: "uninstall"

    - name: "Include role 'git'"
      ansible.builtin.include_role:
        name: "git"
        tasks_from: "uninstall"

    - name: "Include role 'stow'"
      ansible.builtin.include_role:
        name: "stow"
        tasks_from: "uninstall"
