---
utilities_packges:
  - "htop"
  - "btop"
  - "curl"
  - "wget"
  - "vim"
  - "make"
  - "unzip"
  - "ripgrep"
  - "bat"
  - "exa"
  - "duf"
  - "rsync"
  - "dnsutils"
  - "net-tools"
  - "cloc"
  - "build-essential"

utilities_mailpit_install_url: "https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh"
utilities_mailpit_location: "/usr/local/bin/mailpit"

utilities_yt_dlp_download_url: "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux"
utilities_yt_dlp_location: "{{ ansible_env.HOME }}/.local/bin/yt-dlp"
utilities_yt_dlp_fish_sources_download_url: "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.tar.gz"
utilities_yt_dlp_fish_completions_location: "{{ ansible_env.HOME }}/.config/fish/completions/yt-dlp.fish"
