---
utilities_packges:
  - "htop"
  - "btop"
  - "curl"
  - "wget"
  - "vim"
  - "make"
  - "unzip"
  - "bat"
  - "exa"
  - "duf"
  - "rsync"
  - "dnsutils"
  - "net-tools"
  - "cloc"
  - "build-essential"

utilities_mailhog_download_url: "https://github.com/mailhog/mailhog/releases/latest/download/MailHog_linux_amd64"
utilities_mailhog_location: "{{ ansible_env.HOME }}/.local/bin/mailhog"
