---
- name: "Remove Stylua"
  ansible.builtin.file:
    path: "{{ nvim_stylua_install_location }}/stylua"
    state: "absent"

- name: "Remove Nvim configuration"
  stow:
    package: "nvim"
    dir: "{{ modules_path }}"
    target: "{{ ansible_env.HOME }}"
    state: "absent"

- name: "Remove Nvim"
  ansible.builtin.file:
    path: "{{ nvim_install_location }}/nvim"
    state: "absent"
